development:
  adapter: sqlite3
  database: development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: fractal_view_site_production
