development:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: fractal_view_site_dev
  username: stepangolovko
  host: localhost
  port: 5432
test:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: fractal_view_site_test
  host: localhost
  port: 5432
production:
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: fractal_view_site_prod
  host: localhost
  port: 5432
